import fs from 'node:fs';
import path from 'node:path';

export const COMPOSITION_SCHEMA = 'thetree-skin-composition/v1';
export const SLOT_CONTRACT_SCHEMA = 'thetree-skin-slot-contract/v1';
export const SLOT_NAMES = Object.freeze(['desktop', 'mobile']);

export function packageManagerScriptMatches(command, executablePath) {
  if (!command || !executablePath) return false;
  const executableName = path.basename(executablePath).toLowerCase()
    .replace(/-cli(?=\.(?:c?js|mjs)$)/, '')
    .replace(/\.(?:c?js|mjs|cmd)$/i, '');
  return executableName === String(command).toLowerCase();
}

function assertString(value, label) {
  if (typeof value !== 'string' || !value.trim()) throw new Error(`${label} must be a non-empty string.`);
  return value.trim();
}

export function validateComposition(composition) {
  if (composition?.schema !== COMPOSITION_SCHEMA) {
    throw new Error(`Unsupported composition schema ${composition?.schema || 'none'}.`);
  }
  for (const slot of SLOT_NAMES) {
    const value = composition.slots?.[slot];
    assertString(value?.repository, `slots.${slot}.repository`);
    assertString(value?.ref, `slots.${slot}.ref`);
    assertString(value?.contract, `slots.${slot}.contract`);
  }
  return composition;
}

function assertRelativePath(value, label) {
  const relativePath = assertString(value, label);
  if (path.isAbsolute(relativePath) || relativePath.split(/[\\/]/).includes('..')) {
    throw new Error(`${label} escapes its owner.`);
  }
  return relativePath;
}

export function resolveContainedPath(root, relativePath, label) {
  const safeRelativePath = assertRelativePath(relativePath, label);
  const resolvedRoot = path.resolve(root);
  const resolvedPath = path.resolve(root, safeRelativePath);
  if (resolvedPath !== resolvedRoot && !resolvedPath.startsWith(`${resolvedRoot}${path.sep}`)) {
    throw new Error(`${label} escapes its owner.`);
  }
  return resolvedPath;
}

export function validateSlotContract(contract, slot) {
  if (contract?.schema !== SLOT_CONTRACT_SCHEMA) {
    throw new Error(`${slot} slot has unsupported contract schema ${contract?.schema || 'none'}.`);
  }
  assertString(contract.id, `${slot} slot id`);
  const hasEntry = typeof contract.entry === 'string' && contract.entry.trim();
  const hasAdapter = typeof contract.adapter === 'string' && contract.adapter.trim();
  if (Boolean(hasEntry) === Boolean(hasAdapter)) {
    throw new Error(`${slot} slot must declare exactly one of entry or adapter.`);
  }
  if (hasEntry) assertRelativePath(contract.entry, `${slot} slot entry`);
  if (hasAdapter) assertRelativePath(contract.adapter, `${slot} slot adapter`);
  if (contract.contentSurface !== 'host') throw new Error(`${slot} slot must preserve the host content surface.`);
  if (!Array.isArray(contract.configNamespaces)) throw new Error(`${slot} slot must declare configNamespaces.`);
  if (!Array.isArray(contract.sharedConfigKeys)) throw new Error(`${slot} slot must declare sharedConfigKeys.`);
  contract.configNamespaces.forEach((namespace) => assertString(namespace, `${slot} config namespace`));
  contract.sharedConfigKeys.forEach((key) => assertString(key, `${slot} shared config key`));
  assertString(contract.license, `${slot} slot license`);
  if (contract.prepare !== undefined) {
    if (!Array.isArray(contract.prepare) || !contract.prepare.length) {
      throw new Error(`${slot} slot prepare must be a non-empty argument array when declared.`);
    }
    contract.prepare.forEach((word) => assertString(word, `${slot} prepare argument`));
  }
  return contract;
}

export function validateConfigBoundaries(manifests) {
  const owners = new Map();
  for (const slot of SLOT_NAMES) {
    for (const namespace of manifests[slot].configNamespaces) {
      assertString(namespace, `${slot} config namespace`);
      const owner = owners.get(namespace);
      if (owner && owner !== slot) throw new Error(`Config namespace ${namespace} is claimed by ${owner} and ${slot}.`);
      owners.set(namespace, slot);
    }
  }
  return Object.fromEntries(owners);
}

export function renderSlotLoaders(contracts, mobileFrontendContract) {
  const lines = [
    '/* @generated by tools/bootstrap.mjs; do not hand-edit. */',
    "import { defineAsyncComponent } from 'vue';",
    `export const mobileFrontendContract = Object.freeze(${JSON.stringify(mobileFrontendContract)});`,
    'export const slotComponents = Object.freeze({'
  ];
  SLOT_NAMES.forEach((slot, index) => {
    const contract = contracts[slot];
    const importPath = contract.adapter
      ? `../../${contract.adapter.replaceAll('\\', '/')}`
      : `../slots/${slot}/${contract.entry.replaceAll('\\', '/')}`;
    lines.push(`  ${slot}: defineAsyncComponent(() => import('${importPath}'))${index === SLOT_NAMES.length - 1 ? '' : ','}`);
  });
  lines.push('});', '');
  return lines.join('\n');
}

export function makeLicenseInventory(contracts) {
  return {
    schema: 1,
    composerLicense: 'MIT',
    slots: Object.fromEntries(SLOT_NAMES.map((slot) => [slot, {
      id: contracts[slot].id,
      license: contracts[slot].license
    }]))
  };
}

export function readJson(filename) {
  return JSON.parse(fs.readFileSync(filename, 'utf8'));
}

export function writeDeterministicJson(filename, value) {
  fs.mkdirSync(path.dirname(filename), { recursive: true });
  fs.writeFileSync(filename, `${JSON.stringify(value, null, 2)}\n`);
}
