import fs from 'node:fs';
import path from 'node:path';

export const COMPOSITION_SCHEMA = 'thetree-skin-composition/v1';
export const CHILD_SCHEMA = 'thetree-composable-skin/v1';
export const SLOT_NAMES = Object.freeze(['desktop', 'mobile']);

function assertString(value, label) {
  if (typeof value !== 'string' || !value.trim()) throw new Error(`${label} must be a non-empty string.`);
  return value.trim();
}

export function validateComposition(composition) {
  if (composition?.schema !== COMPOSITION_SCHEMA) {
    throw new Error(`Unsupported composition schema ${composition?.schema || 'none'}.`);
  }
  for (const slot of SLOT_NAMES) {
    const value = composition.slots?.[slot];
    assertString(value?.repository, `slots.${slot}.repository`);
    assertString(value?.ref, `slots.${slot}.ref`);
  }
  return composition;
}

export function validateChildManifest(manifest, slot) {
  if (manifest?.schema !== CHILD_SCHEMA) throw new Error(`${slot} child has unsupported schema ${manifest?.schema || 'none'}.`);
  assertString(manifest.id, `${slot} child id`);
  const entry = assertString(manifest.entry, `${slot} child entry`);
  if (path.isAbsolute(entry) || entry.split(/[\\/]/).includes('..')) throw new Error(`${slot} child entry escapes its repository.`);
  if (manifest.contentSurface !== 'host') throw new Error(`${slot} child must preserve the host content surface.`);
  if (!Array.isArray(manifest.configNamespaces) || !manifest.configNamespaces.length) {
    throw new Error(`${slot} child must declare configNamespaces.`);
  }
  if (!Array.isArray(manifest.sharedConfigKeys)) throw new Error(`${slot} child must declare sharedConfigKeys.`);
  assertString(manifest.license, `${slot} child license`);
  return manifest;
}

export function validateConfigBoundaries(manifests) {
  const owners = new Map();
  for (const slot of SLOT_NAMES) {
    for (const namespace of manifests[slot].configNamespaces) {
      assertString(namespace, `${slot} config namespace`);
      const owner = owners.get(namespace);
      if (owner && owner !== slot) throw new Error(`Config namespace ${namespace} is claimed by ${owner} and ${slot}.`);
      owners.set(namespace, slot);
    }
  }
  return Object.fromEntries(owners);
}

export function renderSlotLoaders(manifests, mobileFrontendContract) {
  const lines = [
    '/* @generated by tools/bootstrap.mjs; do not hand-edit. */',
    `export const mobileFrontendContract = Object.freeze(${JSON.stringify(mobileFrontendContract)});`,
    'export const slotComponents = Object.freeze({'
  ];
  SLOT_NAMES.forEach((slot, index) => {
    const entry = manifests[slot].entry.replaceAll('\\', '/');
    lines.push(`  ${slot}: () => import('../slots/${slot}/${entry}')${index === SLOT_NAMES.length - 1 ? '' : ','}`);
  });
  lines.push('});', '');
  return lines.join('\n');
}

export function makeLicenseInventory(manifests) {
  return {
    schema: 1,
    composerLicense: 'MIT',
    slots: Object.fromEntries(SLOT_NAMES.map((slot) => [slot, {
      id: manifests[slot].id,
      license: manifests[slot].license
    }]))
  };
}

export function readJson(filename) {
  return JSON.parse(fs.readFileSync(filename, 'utf8'));
}

export function writeDeterministicJson(filename, value) {
  fs.mkdirSync(path.dirname(filename), { recursive: true });
  fs.writeFileSync(filename, `${JSON.stringify(value, null, 2)}\n`);
}
